name: Makefile CI

on:
  push:
    branches: [ "pipa_global-user-13-RKQ1.211001.001-V14.0.5.0.TMZMIXM-release-keys" ]
  pull_request:
    branches: [ "pipa_global-user-13-RKQ1.211001.001-V14.0.5.0.TMZMIXM-release-keys" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
